# Generated by Selenium IDE
import pytest
import time
import json
import sys
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC

class TestEditTimeAndDoQuiz():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}
  
    def teardown_method(self, method):
        self.driver.quit()
        
    def test(self, *testEditTimeAndDoQuiz_list):
        result = []
        for test in testEditTimeAndDoQuiz_list:
            result.append(test())
            fail_testEditTimeAndDoQuiz_name = []
            for i in range(0, len(result)):
                if not result[i]:
                    fail_testEditTimeAndDoQuiz_name.append(testEditTimeAndDoQuiz_list[i].__name__)

            fail_testEditTimeAndDoQuiz_name_str = 'FAILED:\n\t'+ '\n\t'.join(name for name in fail_testEditTimeAndDoQuiz_name) if len(fail_testEditTimeAndDoQuiz_name) != 0 else 'Fail testcase: None'
            return f"""
            \n- Test Edit Time And Do Quiz (Level 0)--\nPASSED: {result.count(True)}/{len(result)}\n{fail_testEditTimeAndDoQuiz_name_str}\n
            """

    def run(self):
        self.setup_method(None)
        result = self.test(
            self.test_responsive2,
            # self.testEditTimeAndDoQuiz_1,
            # self.testEditTimeAndDoQuiz_2,
            # self.testEditTimeAndDoQuiz_3,
            # self.testEditTimeAndDoQuiz_4,
            # self.testEditTimeAndDoQuiz_5,
            # self.testEditTimeAndDoQuiz_6,
            # self.testEditTimeAndDoQuiz_7,
            # self.testEditTimeAndDoQuiz_8,
            # self.testEditTimeAndDoQuiz_9,
            # self.testEditTimeAndDoQuiz_10,
        )
        self.teardown_method(None)
        return result
    
    def test_responsive2(self):
        self.driver.get("https://school.moodledemo.net/")
        self.driver.set_window_size(1056, 804)
        self.driver.find_element(By.LINK_TEXT, "Log in").click()
        self.driver.find_element(By.ID, "username").click()
        self.driver.find_element(By.ID, "username").send_keys("teacher")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("moodle")
        self.driver.find_element(By.ID, "loginbtn").click()
        time.sleep(5)
        self.driver.find_element(By.XPATH, "//div[3]/div/div/div/a/span[3]").click()
        self.driver.find_element(By.LINK_TEXT, "Quizzes").click()
        self.driver.find_element(By.XPATH, "//li[@id=\'module-703\']/div/div[2]/div/div/div/div/a").click()
        self.driver.find_element(By.LINK_TEXT, "Settings").click()
        self.driver.find_element(By.ID, "collapseElement-1").click()
        self.driver.find_element(By.ID, "id_timeopen_day").click()
        self.driver.find_element(By.ID, "id_timelimit_number").click()
        self.driver.find_element(By.ID, "id_timelimit_number").send_keys("5")
        time.sleep(5);
        self.driver.find_element(By.ID, "id_submitbutton2").click()
        self.driver.find_element(By.ID, "user-menu-toggle").click()
        self.driver.find_element(By.LINK_TEXT, "Log out").click()
        self.driver.close()
        return True
    
    def test_responsive1(self):
        self.driver.get("https://school.moodledemo.net/")
        self.driver.set_window_size(1056, 804)
        self.driver.find_element(By.LINK_TEXT, "Log in").click()
        self.driver.find_element(By.ID, "username").click()
        self.driver.find_element(By.ID, "username").send_keys("teacher")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("moodle")
        self.driver.find_element(By.ID, "loginbtn").click()
        time.sleep(3)
        self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").click();
        self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").send_keys("mind")
        self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").send_keys(Keys.ENTER)
        time.sleep(3)
        self.driver.find_element(By.XPATH, "//span[3]").click()
        time.sleep(3)
        self.driver.find_element(By.CSS_SELECTOR, ".modtype_quiz .aalink").click()
        self.driver.find_element(By.LINK_TEXT, "Settings").click()
        time.sleep(5)
        self.driver.find_element(By.ID, "collapseElement-1").click()
        self.driver.find_element(By.ID, "id_timeopen_day").click()
        self.driver.find_element(By.ID, "id_timelimit_number").click()
        self.driver.find_element(By.ID, "id_timelimit_number").send_keys("1")
        self.driver.find_element(By.ID, "id_timelimit_number").send_keys(Keys.ENTER)
        self.driver.find_element(By.ID, "id_submitbutton").click()
        self.driver.find_element(By.ID, "user-menu-toggle").click()
        self.driver.find_element(By.LINK_TEXT, "Log out").click()
        self.driver.close()
        return True
    
    def testEditTimeAndDoQuiz_1(self):
        print(sys._getframe(0).f_code.co_name)
        try:
            self.driver.get("https://school.moodledemo.net/")
            self.driver.set_window_size(790, 816)
            self.driver.find_element(By.LINK_TEXT, "Log in").click()
            self.driver.find_element(By.CSS_SELECTOR, ".login-container").click()
            self.driver.find_element(By.ID, "username").click()
            self.driver.find_element(By.ID, "username").send_keys("teacher")
            self.driver.find_element(By.ID, "password").click()
            self.driver.find_element(By.ID, "password").send_keys("moodle")
            self.driver.find_element(By.ID, "loginbtn").click()
            time.sleep(3)
            self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").click();
            self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").send_keys("mind")
            self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").send_keys(Keys.ENTER)
            time.sleep(3)
            self.driver.find_element(By.XPATH, "//span[3]").click()
            self.driver.find_element(By.CSS_SELECTOR, ".modtype_quiz .aalink").click()
            self.driver.find_element(By.CSS_SELECTOR, ".nav-tabs > li:nth-child(2) > a").click()
            time.sleep(5)
            self.driver.execute_script("window.scrollTo(0,391)")
            self.driver.find_element(By.ID, "collapseElement-1").click()
            time.sleep(3)
            self.driver.find_element(By.ID, "id_timelimit_number").click()
            self.driver.find_element(By.ID, "id_timelimit_number").send_keys("1")
            self.driver.find_element(By.ID, "id_timelimit_number").send_keys(Keys.ENTER)
            self.driver.execute_script("window.scrollTo(400,400)")
            time.sleep(3)
            self.driver.find_element(By.ID, "id_submitbutton").click()
            time.sleep(3)
            # self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
            # time.sleep(3)
            # self.driver.find_element(By.CSS_SELECTOR, ".moodle-dialogue .btn-primary").click()
            # self.driver.execute_script("window.scrollTo(222,222)")
            # self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
            # self.driver.execute_script("window.scrollTo(100,100)")
            # self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
            # time.sleep(3)
            # self.driver.find_element(By.CSS_SELECTOR, ".modal-footer > button:nth-child(2)").click()
            return True
        
        except Exception as err:
            print(f"Unexpected {err=}, {type(err)=}")
            self.driver.find_element(By.ID, "user-menu-toggle").click()
            self.driver.find_element(By.LINK_TEXT, "Log out").click()
            return False
    
    def testEditTimeAndDoQuiz_2(self):
        print(sys._getframe(0).f_code.co_name)
        try:
            self.driver.get("https://school.moodledemo.net/")
            self.driver.set_window_size(790, 816)
            self.driver.find_element(By.LINK_TEXT, "Log in").click()
            self.driver.find_element(By.CSS_SELECTOR, ".login-container").click()
            self.driver.find_element(By.ID, "username").click()
            self.driver.find_element(By.ID, "username").send_keys("teacher")
            self.driver.find_element(By.ID, "password").click()
            self.driver.find_element(By.ID, "password").send_keys("moodle")
            self.driver.find_element(By.ID, "loginbtn").click()
            time.sleep(3)
            self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").click();
            self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").send_keys("mind")
            self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").send_keys(Keys.ENTER)
            time.sleep(3)
            self.driver.find_element(By.XPATH, "//span[3]").click()
            self.driver.find_element(By.CSS_SELECTOR, ".modtype_quiz .aalink").click()
            self.driver.find_element(By.CSS_SELECTOR, ".nav-tabs > li:nth-child(2) > a").click()
            self.driver.execute_script("window.scrollTo(0,391)")
            self.driver.find_element(By.ID, "collapseElement-1").click()
            self.driver.find_element(By.ID, "id_timelimit_number").click()
            self.driver.find_element(By.ID, "id_timelimit_number").send_keys("0")
            time.sleep(3)
            self.driver.execute_script("window.scrollTo(200,200)")
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary:nth-child(2)").click()
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
            time.sleep(3)
            self.driver.find_element(By.CSS_SELECTOR, ".moodle-dialogue .btn-primary").click()
            self.driver.execute_script("window.scrollTo(222,222)")
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
            self.driver.execute_script("window.scrollTo(100,100)")
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
            time.sleep(3)
            self.driver.find_element(By.CSS_SELECTOR, ".modal-footer > button:nth-child(2)").click()
            time.sleep(5)
            return True
        
        except Exception as err:
            print(f"Unexpected {err=}, {type(err)=}")
            self.driver.find_element(By.ID, "user-menu-toggle").click()
            self.driver.find_element(By.LINK_TEXT, "Log out").click()
            return False
       
    def testEditTimeAndDoQuiz_3(self):
        print(sys._getframe(0).f_code.co_name)
        try:
            self.driver.get("https://school.moodledemo.net/")
            self.driver.set_window_size(790, 816)
            self.driver.find_element(By.LINK_TEXT, "Log in").click()
            self.driver.find_element(By.CSS_SELECTOR, ".login-container").click()
            self.driver.find_element(By.ID, "username").click()
            self.driver.find_element(By.ID, "username").send_keys("teacher")
            self.driver.find_element(By.ID, "password").click()
            self.driver.find_element(By.ID, "password").send_keys("moodle")
            self.driver.find_element(By.ID, "loginbtn").click()
            time.sleep(3)
            self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").click();
            self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").send_keys("mind")
            self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").send_keys(Keys.ENTER)
            time.sleep(3)
            self.driver.find_element(By.XPATH, "//span[3]").click()
            self.driver.find_element(By.CSS_SELECTOR, ".modtype_quiz .aalink").click()
            self.driver.find_element(By.CSS_SELECTOR, ".nav-tabs > li:nth-child(2) > a").click()
            self.driver.execute_script("window.scrollTo(0,391)")
            self.driver.find_element(By.ID, "collapseElement-1").click()
            self.driver.find_element(By.ID, "id_timelimit_number").click()
            self.driver.find_element(By.ID, "id_timelimit_number").send_keys("15")
            time.sleep(3)
            self.driver.execute_script("window.scrollTo(200,200)")
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary:nth-child(2)").click()
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
            time.sleep(3)
            self.driver.find_element(By.CSS_SELECTOR, ".moodle-dialogue .btn-primary").click()
            self.driver.execute_script("window.scrollTo(222,222)")
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
            self.driver.execute_script("window.scrollTo(100,100)")
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
            time.sleep(3)
            self.driver.find_element(By.CSS_SELECTOR, ".modal-footer > button:nth-child(2)").click()
            time.sleep(5)
            return True
        
        except Exception as err:
            print(f"Unexpected {err=}, {type(err)=}")
            self.driver.find_element(By.ID, "user-menu-toggle").click()
            self.driver.find_element(By.LINK_TEXT, "Log out").click()
            return False
    
    def testEditTimeAndDoQuiz_4(self):
        print(sys._getframe(0).f_code.co_name)
        try:
            self.driver.get("https://school.moodledemo.net/")
            self.driver.set_window_size(790, 816)
            self.driver.find_element(By.LINK_TEXT, "Log in").click()
            self.driver.find_element(By.CSS_SELECTOR, ".login-container").click()
            self.driver.find_element(By.ID, "username").click()
            self.driver.find_element(By.ID, "username").send_keys("teacher")
            self.driver.find_element(By.ID, "password").click()
            self.driver.find_element(By.ID, "password").send_keys("moodle")
            self.driver.find_element(By.ID, "loginbtn").click()
            time.sleep(3)
            self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").click();
            self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").send_keys("mind")
            self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").send_keys(Keys.ENTER)
            time.sleep(3)
            self.driver.find_element(By.XPATH, "//span[3]").click()
            self.driver.find_element(By.CSS_SELECTOR, ".modtype_quiz .aalink").click()
            self.driver.find_element(By.CSS_SELECTOR, ".nav-tabs > li:nth-child(2) > a").click()
            self.driver.execute_script("window.scrollTo(0,391)")
            self.driver.find_element(By.ID, "collapseElement-1").click()
            self.driver.find_element(By.ID, "id_timelimit_number").click()
            self.driver.find_element(By.ID, "id_timelimit_number").send_keys("abc2yugwvywuwyv22vw727wg9w82g92g929g29g29gg")
            time.sleep(3)
            self.driver.execute_script("window.scrollTo(200,200)")
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary:nth-child(2)").click()
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
            time.sleep(3)
            self.driver.find_element(By.CSS_SELECTOR, ".moodle-dialogue .btn-primary").click()
            self.driver.execute_script("window.scrollTo(222,222)")
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
            self.driver.execute_script("window.scrollTo(100,100)")
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
            time.sleep(3)
            self.driver.find_element(By.CSS_SELECTOR, ".modal-footer > button:nth-child(2)").click()
            time.sleep(5)
            return True
        
        except Exception as err:
            print(f"Unexpected {err=}, {type(err)=}")
            self.driver.find_element(By.ID, "user-menu-toggle").click()
            self.driver.find_element(By.LINK_TEXT, "Log out").click()
            return False
       
    def testEditTimeAndDoQuiz_5(self):
        print(sys._getframe(0).f_code.co_name)
        try:
            self.driver.get("https://school.moodledemo.net/")
            self.driver.set_window_size(790, 816)
            self.driver.find_element(By.LINK_TEXT, "Log in").click()
            self.driver.find_element(By.CSS_SELECTOR, ".login-container").click()
            self.driver.find_element(By.ID, "username").click()
            self.driver.find_element(By.ID, "username").send_keys("teacher")
            self.driver.find_element(By.ID, "password").click()
            self.driver.find_element(By.ID, "password").send_keys("moodle")
            self.driver.find_element(By.ID, "loginbtn").click()
            time.sleep(3)
            self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").click();
            self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").send_keys("mind")
            self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").send_keys(Keys.ENTER)
            time.sleep(3)
            self.driver.find_element(By.XPATH, "//span[3]").click()
            self.driver.find_element(By.CSS_SELECTOR, ".modtype_quiz .aalink").click()
            self.driver.find_element(By.CSS_SELECTOR, ".nav-tabs > li:nth-child(2) > a").click()
            self.driver.execute_script("window.scrollTo(0,391)")
            self.driver.find_element(By.ID, "collapseElement-1").click()
            self.driver.find_element(By.ID, "id_timelimit_number").click()
            self.driver.find_element(By.ID, "id_timelimit_number").send_keys("@121232434343434343")
            time.sleep(3)
            self.driver.execute_script("window.scrollTo(200,200)")
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary:nth-child(2)").click()
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
            time.sleep(3)
            self.driver.find_element(By.CSS_SELECTOR, ".moodle-dialogue .btn-primary").click()
            self.driver.execute_script("window.scrollTo(222,222)")
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
            self.driver.execute_script("window.scrollTo(100,100)")
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
            time.sleep(3)
            self.driver.find_element(By.CSS_SELECTOR, ".modal-footer > button:nth-child(2)").click()
            time.sleep(5)
            return True
        
        except Exception as err:
            print(f"Unexpected {err=}, {type(err)=}")
            self.driver.find_element(By.ID, "user-menu-toggle").click()
            self.driver.find_element(By.LINK_TEXT, "Log out").click()
            return False
        
    def testEditTimeAndDoQuiz_6(self):
        print(sys._getframe(0).f_code.co_name)
        try:
            self.driver.get("https://school.moodledemo.net/")
            self.driver.set_window_size(790, 816)
            self.driver.find_element(By.LINK_TEXT, "Log in").click()
            self.driver.find_element(By.CSS_SELECTOR, ".login-container").click()
            self.driver.find_element(By.ID, "username").click()
            self.driver.find_element(By.ID, "username").send_keys("teacher")
            self.driver.find_element(By.ID, "password").click()
            self.driver.find_element(By.ID, "password").send_keys("moodle")
            self.driver.find_element(By.ID, "loginbtn").click()
            time.sleep(3)
            self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").click();
            self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").send_keys("mind")
            self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").send_keys(Keys.ENTER)
            time.sleep(3)
            self.driver.find_element(By.XPATH, "//span[3]").click()
            self.driver.find_element(By.CSS_SELECTOR, ".modtype_quiz .aalink").click()
            self.driver.find_element(By.CSS_SELECTOR, ".nav-tabs > li:nth-child(2) > a").click()
            self.driver.execute_script("window.scrollTo(0,391)")
            self.driver.find_element(By.ID, "collapseElement-1").click()
            self.driver.find_element(By.ID, "id_timelimit_number").click()
            self.driver.find_element(By.ID, "id_timelimit_number").send_keys("INSERT malware to db.quiz")
            time.sleep(3)
            self.driver.execute_script("window.scrollTo(200,200)")
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary:nth-child(2)").click()
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
            time.sleep(3)
            self.driver.find_element(By.CSS_SELECTOR, ".moodle-dialogue .btn-primary").click()
            self.driver.execute_script("window.scrollTo(222,222)")
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
            self.driver.execute_script("window.scrollTo(100,100)")
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
            time.sleep(3)
            self.driver.find_element(By.CSS_SELECTOR, ".modal-footer > button:nth-child(2)").click()
            time.sleep(5)
            return True
        
        except Exception as err:
            print(f"Unexpected {err=}, {type(err)=}")
            self.driver.find_element(By.ID, "user-menu-toggle").click()
            self.driver.find_element(By.LINK_TEXT, "Log out").click()
            return False
       
    def testEditTimeAndDoQuiz_7(self):
        print(sys._getframe(0).f_code.co_name)
        try:
            self.driver.get("https://school.moodledemo.net/")
            self.driver.set_window_size(790, 816)
            self.driver.find_element(By.LINK_TEXT, "Log in").click()
            self.driver.find_element(By.CSS_SELECTOR, ".login-container").click()
            self.driver.find_element(By.ID, "username").click()
            self.driver.find_element(By.ID, "username").send_keys("teacher")
            self.driver.find_element(By.ID, "password").click()
            self.driver.find_element(By.ID, "password").send_keys("moodle")
            self.driver.find_element(By.ID, "loginbtn").click()
            time.sleep(3)
            self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").click();
            self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").send_keys("mind")
            self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").send_keys(Keys.ENTER)
            time.sleep(3)
            self.driver.find_element(By.XPATH, "//span[3]").click()
            self.driver.find_element(By.CSS_SELECTOR, ".modtype_quiz .aalink").click()
            self.driver.find_element(By.CSS_SELECTOR, ".nav-tabs > li:nth-child(2) > a").click()
            self.driver.execute_script("window.scrollTo(0,391)")
            self.driver.find_element(By.ID, "collapseElement-1").click()
            self.driver.find_element(By.ID, "id_timelimit_number").click()
            self.driver.find_element(By.ID, "id_timelimit_number").send_keys("99999999999999999999999999999999")
            time.sleep(3)
            self.driver.execute_script("window.scrollTo(200,200)")
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary:nth-child(2)").click()
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
            time.sleep(3)
            self.driver.find_element(By.CSS_SELECTOR, ".moodle-dialogue .btn-primary").click()
            self.driver.execute_script("window.scrollTo(222,222)")
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
            self.driver.execute_script("window.scrollTo(100,100)")
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
            time.sleep(3)
            self.driver.find_element(By.CSS_SELECTOR, ".modal-footer > button:nth-child(2)").click()
            time.sleep(5)
            return True
        
        except Exception as err:
            print(f"Unexpected {err=}, {type(err)=}")
            self.driver.find_element(By.ID, "user-menu-toggle").click()
            self.driver.find_element(By.LINK_TEXT, "Log out").click()
            return False
        
    def testEditTimeAndDoQuiz_8(self):
        print(sys._getframe(0).f_code.co_name)
        try:
            self.driver.get("https://school.moodledemo.net/")
            self.driver.set_window_size(790, 816)
            self.driver.find_element(By.LINK_TEXT, "Log in").click()
            self.driver.find_element(By.CSS_SELECTOR, ".login-container").click()
            self.driver.find_element(By.ID, "username").click()
            self.driver.find_element(By.ID, "username").send_keys("teacher")
            self.driver.find_element(By.ID, "password").click()
            self.driver.find_element(By.ID, "password").send_keys("moodle")
            self.driver.find_element(By.ID, "loginbtn").click()
            time.sleep(3)
            self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").click();
            self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").send_keys("mind")
            self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").send_keys(Keys.ENTER)
            time.sleep(3)
            self.driver.find_element(By.XPATH, "//span[3]").click()
            self.driver.find_element(By.CSS_SELECTOR, ".modtype_quiz .aalink").click()
            self.driver.find_element(By.CSS_SELECTOR, ".nav-tabs > li:nth-child(2) > a").click()
            self.driver.execute_script("window.scrollTo(0,391)")
            self.driver.find_element(By.ID, "collapseElement-1").click()
            self.driver.find_element(By.ID, "id_timelimit_number").click()
            self.driver.find_element(By.ID, "id_timelimit_number").send_keys("-100000000000000000000000")
            time.sleep(3)
            self.driver.execute_script("window.scrollTo(200,200)")
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary:nth-child(2)").click()
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
            time.sleep(3)
            self.driver.find_element(By.CSS_SELECTOR, ".moodle-dialogue .btn-primary").click()
            self.driver.execute_script("window.scrollTo(222,222)")
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
            self.driver.execute_script("window.scrollTo(100,100)")
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
            time.sleep(3)
            self.driver.find_element(By.CSS_SELECTOR, ".modal-footer > button:nth-child(2)").click()
            time.sleep(5)
            return True
        
        except Exception as err:
            print(f"Unexpected {err=}, {type(err)=}")
            self.driver.find_element(By.ID, "user-menu-toggle").click()
            self.driver.find_element(By.LINK_TEXT, "Log out").click()
            return False
        
    def testEditTimeAndDoQuiz_9(self):
        print(sys._getframe(0).f_code.co_name)
        try:
            self.driver.get("https://school.moodledemo.net/")
            self.driver.set_window_size(790, 816)
            self.driver.find_element(By.LINK_TEXT, "Log in").click()
            self.driver.find_element(By.CSS_SELECTOR, ".login-container").click()
            self.driver.find_element(By.ID, "username").click()
            self.driver.find_element(By.ID, "username").send_keys("teacher")
            self.driver.find_element(By.ID, "password").click()
            self.driver.find_element(By.ID, "password").send_keys("moodle")
            self.driver.find_element(By.ID, "loginbtn").click()
            time.sleep(3)
            self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").click();
            self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").send_keys("mind")
            self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").send_keys(Keys.ENTER)
            time.sleep(3)
            self.driver.find_element(By.XPATH, "//span[3]").click()
            self.driver.find_element(By.CSS_SELECTOR, ".modtype_quiz .aalink").click()
            self.driver.find_element(By.CSS_SELECTOR, ".nav-tabs > li:nth-child(2) > a").click()
            self.driver.execute_script("window.scrollTo(0,391)")
            self.driver.find_element(By.ID, "collapseElement-1").click()
            self.driver.find_element(By.ID, "id_timelimit_number").click()
            self.driver.find_element(By.ID, "id_timelimit_number").send_keys("+1000000")
            time.sleep(3)
            self.driver.execute_script("window.scrollTo(200,200)")
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary:nth-child(2)").click()
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
            time.sleep(3)
            self.driver.find_element(By.CSS_SELECTOR, ".moodle-dialogue .btn-primary").click()
            self.driver.execute_script("window.scrollTo(222,222)")
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
            self.driver.execute_script("window.scrollTo(100,100)")
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
            time.sleep(3)
            self.driver.find_element(By.CSS_SELECTOR, ".modal-footer > button:nth-child(2)").click()
            time.sleep(5)
            return True
        
        except Exception as err:
            print(f"Unexpected {err=}, {type(err)=}")
            self.driver.find_element(By.ID, "user-menu-toggle").click()
            self.driver.find_element(By.LINK_TEXT, "Log out").click()
            return False
        
    def testEditTimeAndDoQuiz_10(self):
        print(sys._getframe(0).f_code.co_name)
        try:
            self.driver.get("https://school.moodledemo.net/")
            self.driver.set_window_size(790, 816)
            self.driver.find_element(By.LINK_TEXT, "Log in").click()
            self.driver.find_element(By.CSS_SELECTOR, ".login-container").click()
            self.driver.find_element(By.ID, "username").click()
            self.driver.find_element(By.ID, "username").send_keys("teacher")
            self.driver.find_element(By.ID, "password").click()
            self.driver.find_element(By.ID, "password").send_keys("moodle")
            self.driver.find_element(By.ID, "loginbtn").click()
            time.sleep(3)
            self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").click();
            self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").send_keys("mind")
            self.driver.find_element(By.CSS_SELECTOR, ".searchbar input.form-control").send_keys(Keys.ENTER)
            time.sleep(3)
            self.driver.find_element(By.XPATH, "//span[3]").click()
            self.driver.find_element(By.CSS_SELECTOR, ".modtype_quiz .aalink").click()
            self.driver.find_element(By.CSS_SELECTOR, ".nav-tabs > li:nth-child(2) > a").click()
            self.driver.execute_script("window.scrollTo(0,391)")
            self.driver.find_element(By.ID, "collapseElement-1").click()
            self.driver.find_element(By.ID, "id_timelimit_number").click()
            self.driver.find_element(By.ID, "id_timelimit_number").send_keys("#$%^&(*)#")
            time.sleep(3)
            self.driver.execute_script("window.scrollTo(200,200)")
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary:nth-child(2)").click()
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
            time.sleep(3)
            self.driver.find_element(By.CSS_SELECTOR, ".moodle-dialogue .btn-primary").click()
            self.driver.execute_script("window.scrollTo(222,222)")
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
            self.driver.execute_script("window.scrollTo(100,100)")
            self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
            time.sleep(3)
            self.driver.find_element(By.CSS_SELECTOR, ".modal-footer > button:nth-child(2)").click()
            time.sleep(5)
            return True
        
        except Exception as err:
            print(f"Unexpected {err=}, {type(err)=}")
            self.driver.find_element(By.ID, "user-menu-toggle").click()
            self.driver.find_element(By.LINK_TEXT, "Log out").click()
            return False
        
editTimeAndDoQuiz = TestEditTimeAndDoQuiz()
print(editTimeAndDoQuiz.run())
  


  
