# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUserCourse():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_userCourse1(self):
    self.driver.get("https://school.moodledemo.net/")
    self.driver.set_window_size(784, 816)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("teacher")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("moodle")
    self.driver.find_element(By.ID, "loginbtn").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "#course-info-container-69-4 .multiline").click()
    self.driver.find_element(By.LINK_TEXT, "Participants").click()
    self.driver.find_element(By.CSS_SELECTOR, "#enrolusersbutton-1 .btn").click()
    time.sleep(3)
    self.driver.find_element(By.XPATH, "//div[3]/input").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.XPATH, "//div[3]/input").send_keys("stephanadams175@example.com")
    self.driver.find_element(By.ID, "id_userlist_label").click()
    self.driver.find_element(By.ID, "id_cohortlist_label").click()
    self.driver.find_element(By.XPATH, "//div[2]/div[2]/div[3]/input").send_keys("Middle School Students")
    self.driver.find_element(By.ID, "id_cohortlist_label").click()
    self.driver.find_element(By.ID, "id_roletoassign").click()
    time.sleep(1)
    self.driver.find_element(By.XPATH, "//div[2]/div/div/div[3]/button[2]").click()
    time.sleep(3)
    self.driver.execute_script("window.scrollTo(0,400)")
    self.driver.find_element(By.XPATH, "//div[3]/table/tbody/tr/td[2]").click()
    elements = self.driver.find_elements(By.XPATH, "//div[3]/table/tbody/tr/td[2]")
    
    if len(elements) > 0: 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return True
    else: 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return False
  
  def test_userCourse2(self):
    self.driver.get("https://school.moodledemo.net/")
    self.driver.set_window_size(784, 816)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.ID, "password").send_keys("moodle")
    self.driver.find_element(By.ID, "loginbtn").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "#course-info-container-69-4 .multiline").click()
    self.driver.find_element(By.LINK_TEXT, "Participants").click()
    self.driver.find_element(By.CSS_SELECTOR, "#enrolusersbutton-1 .btn").click()
    time.sleep(3)
    self.driver.find_element(By.XPATH, "//div[3]/input").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.XPATH, "//div[3]/input").send_keys("")
    self.driver.find_element(By.ID, "id_userlist_label").click()
    self.driver.find_element(By.ID, "id_cohortlist_label").click()
    self.driver.find_element(By.XPATH, "//div[2]/div[2]/div[3]/input").send_keys("Green House")
    self.driver.find_element(By.ID, "id_cohortlist_label").click()
    self.driver.find_element(By.ID, "id_roletoassign").click()
    time.sleep(1)
    self.driver.find_element(By.XPATH, "//div[2]/div/div/div[3]/button[2]").click()
    time.sleep(3)
    self.driver.execute_script("window.scrollTo(0,400)")
    
    if self.driver.find_element(By.CSS_SELECTOR, ".toast-message").text == "0 enrolled users": 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return True
    else: 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return False
  
  def test_userCourse4(self):
    self.driver.get("https://school.moodledemo.net/")
    self.driver.set_window_size(784, 816)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.ID, "password").send_keys("moodle")
    self.driver.find_element(By.ID, "loginbtn").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "#course-info-container-69-4 .multiline").click()
    self.driver.find_element(By.LINK_TEXT, "Participants").click()
    self.driver.find_element(By.CSS_SELECTOR, "#enrolusersbutton-1 .btn").click()
    time.sleep(3)
    self.driver.find_element(By.XPATH, "//div[3]/input").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.XPATH, "//div[3]/input").send_keys("test@example.com")
    self.driver.find_element(By.ID, "id_userlist_label").click()
    self.driver.find_element(By.ID, "id_cohortlist_label").click()
    self.driver.find_element(By.XPATH, "//div[2]/div[2]/div[3]/input").send_keys("Blue House")
    self.driver.find_element(By.ID, "id_cohortlist_label").click()
    self.driver.find_element(By.ID, "id_roletoassign").click()
    time.sleep(1)
    self.driver.find_element(By.XPATH, "//div[2]/div/div/div[3]/button[2]").click()
    time.sleep(3)
    self.driver.execute_script("window.scrollTo(0,400)")
    
    if self.driver.find_element(By.CSS_SELECTOR, ".toast-message").text == "0 enrolled users": 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return True
    else: 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return False
  
  def test_userCourse5(self):
    self.driver.get("https://school.moodledemo.net/")
    self.driver.set_window_size(784, 816)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()

    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("moodle")
    self.driver.find_element(By.ID, "loginbtn").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "#course-info-container-69-4 .multiline").click()
    self.driver.find_element(By.LINK_TEXT, "Participants").click()
    self.driver.find_element(By.CSS_SELECTOR, "#enrolusersbutton-1 .btn").click()
    time.sleep(3)
    self.driver.find_element(By.XPATH, "//div[3]/input").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.XPATH, "//div[3]/input").send_keys("cathericruz306@example.com")
    self.driver.find_element(By.ID, "id_userlist_label").click()
    self.driver.find_element(By.ID, "id_cohortlist_label").click()
    self.driver.find_element(By.XPATH, "//div[2]/div[2]/div[3]/input").send_keys("Blue House")
    self.driver.find_element(By.ID, "id_cohortlist_label").click()
    self.driver.find_element(By.ID, "id_roletoassign").click()
    dropdown = self.driver.find_element(By.ID, "id_roletoassign")
    select = Select(dropdown)
    select.select_by_value('4')
    time.sleep(1)
    self.driver.find_element(By.XPATH, "//div[2]/div/div/div[3]/button[2]").click()
    time.sleep(3)
    self.driver.execute_script("window.scrollTo(0,400)")
    self.driver.find_element(By.XPATH, "//div[3]/table/tbody/tr/td[2]").click()
    self.driver.find_element(By.ID, "user-index-participants-69_r2").click()
    
    if self.driver.find_element(By.XPATH, "//td[contains(.,\'cathericruz306@example.com\')]").text == "cathericruz306@example.com": 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return True
    else: 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return False
  
  def test_userCourse7(self):
    self.driver.get("https://school.moodledemo.net/")
    self.driver.set_window_size(784, 816)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    
    self.driver.find_element(By.ID, "password").send_keys("moodle")
    self.driver.find_element(By.ID, "loginbtn").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "#course-info-container-69-4 .multiline").click()
    self.driver.find_element(By.LINK_TEXT, "Participants").click()
    self.driver.find_element(By.CSS_SELECTOR, "#enrolusersbutton-1 .btn").click()
    time.sleep(3)
    self.driver.find_element(By.XPATH, "//div[3]/input").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.XPATH, "//div[3]/input").send_keys("francesbanks1@example.com")
    self.driver.find_element(By.ID, "id_userlist_label").click()
    self.driver.find_element(By.ID, "id_cohortlist_label").click()
    self.driver.find_element(By.XPATH, "//div[2]/div[2]/div[3]/input").send_keys("")
    self.driver.find_element(By.ID, "id_cohortlist_label").click()
    self.driver.find_element(By.ID, "id_roletoassign").click()
    dropdown = self.driver.find_element(By.ID, "id_roletoassign")
    select = Select(dropdown)
    select.select_by_value('4')
    time.sleep(1)
    self.driver.find_element(By.XPATH, "//div[2]/div/div/div[3]/button[2]").click()
    time.sleep(3)
    self.driver.execute_script("window.scrollTo(0,400)")
    self.driver.find_element(By.XPATH, "//div[3]/table/tbody/tr/td[2]").click()
    
    if self.driver.find_element(By.CSS_SELECTOR, ".toast-message").text == "0 enrolled users": 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return True
    else: 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return False
  
  def test_userCourse8(self):
    self.driver.get("https://school.moodledemo.net/")
    self.driver.set_window_size(784, 816)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    
    self.driver.find_element(By.ID, "password").send_keys("moodle")
    self.driver.find_element(By.ID, "loginbtn").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "#course-info-container-69-4 .multiline").click()
    self.driver.find_element(By.LINK_TEXT, "Participants").click()
    self.driver.find_element(By.CSS_SELECTOR, "#enrolusersbutton-1 .btn").click()
    time.sleep(3)
    self.driver.find_element(By.XPATH, "//div[3]/input").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.XPATH, "//div[3]/input").send_keys("test@example.com")
    self.driver.find_element(By.ID, "id_userlist_label").click()
    self.driver.find_element(By.ID, "id_cohortlist_label").click()
    self.driver.find_element(By.XPATH, "//div[2]/div[2]/div[3]/input").send_keys("Teaching Staff")
    self.driver.find_element(By.ID, "id_cohortlist_label").click()
    self.driver.find_element(By.ID, "id_roletoassign").click()
    dropdown = self.driver.find_element(By.ID, "id_roletoassign")
    select = Select(dropdown)
    select.select_by_value('4')
    time.sleep(1)
    self.driver.find_element(By.XPATH, "//div[2]/div/div/div[3]/button[2]").click()
    time.sleep(3)
    self.driver.execute_script("window.scrollTo(0,400)")
    self.driver.find_element(By.XPATH, "//div[3]/table/tbody/tr/td[2]").click()
    
    if self.driver.find_element(By.CSS_SELECTOR, ".toast-message").text == "0 enrolled users": 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return True
    else: 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return False
  
  def test_userCourse9(self):
    self.driver.get("https://school.moodledemo.net/")
    self.driver.set_window_size(784, 816)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    
    self.driver.find_element(By.ID, "password").send_keys("moodle")
    self.driver.find_element(By.ID, "loginbtn").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "#course-info-container-69-4 .multiline").click()
    self.driver.find_element(By.LINK_TEXT, "Participants").click()
    self.driver.find_element(By.CSS_SELECTOR, "#enrolusersbutton-1 .btn").click()
    time.sleep(3)
    self.driver.find_element(By.XPATH, "//div[3]/input").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.XPATH, "//div[3]/input").send_keys("stephanadams175@example.com")
    self.driver.find_element(By.ID, "id_userlist_label").click()
    self.driver.find_element(By.ID, "id_cohortlist_label").click()
    self.driver.find_element(By.XPATH, "//div[2]/div[2]/div[3]/input").send_keys("Blue House")
    self.driver.find_element(By.ID, "id_cohortlist_label").click()
    self.driver.find_element(By.ID, "id_roletoassign").click()
    time.sleep(1)
    self.driver.find_element(By.XPATH, "//div[2]/div/div/div[3]/button[2]").click()
    time.sleep(3)
    text = self.driver.find_element(By.CSS_SELECTOR, ".toast-message").text
    
    if text != "0 enrolled users": 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return True
    else: 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return False
  
  def test_userCourse10(self):
    self.driver.get("https://school.moodledemo.net/")
    self.driver.set_window_size(783, 816)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()

    self.driver.find_element(By.ID, "password").send_keys("moodle")
    self.driver.find_element(By.ID, "loginbtn").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "#course-info-container-69-4 .multiline").click()
    self.driver.find_element(By.LINK_TEXT, "Participants").click()
    self.driver.find_element(By.CSS_SELECTOR, "#enrolusersbutton-1 .btn").click()
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "#enrolusersbutton-1 .btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.XPATH, "//div[3]/input").click()
    self.driver.find_element(By.XPATH, "//div[3]/input").send_keys("se")
    time.sleep(2)
    self.driver.find_element(By.XPATH, "//div[2]/div/div[2]/ul/li").click()
    self.driver.find_element(By.XPATH, "//div[2]/div[2]/div[3]/input").send_keys("Blue House")
    time.sleep(1)
    self.driver.find_element(By.XPATH, "//div[2]/div/div/div[3]/button[2]").click()
    time.sleep(3)
    text = self.driver.find_element(By.CSS_SELECTOR, ".toast-message").text
    
    if text != "0 enrolled users": 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return True
    else: 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return False
  
  def test_userCourse11(self):
    self.driver.get("https://school.moodledemo.net/")
    self.driver.set_window_size(783, 816)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()

    self.driver.find_element(By.ID, "password").send_keys("moodle")
    self.driver.find_element(By.ID, "loginbtn").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "#course-info-container-69-4 .multiline").click()
    self.driver.find_element(By.LINK_TEXT, "Participants").click()
    self.driver.find_element(By.CSS_SELECTOR, "#enrolusersbutton-1 .btn").click()
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "#enrolusersbutton-1 .btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.XPATH, "//div[3]/input").click()
    self.driver.find_element(By.XPATH, "//div[3]/input").send_keys("stevenmoreno331@example.com")
    self.driver.find_element(By.XPATH, "//div[2]/div[2]/div[3]/input").send_keys("Blue")
    time.sleep(1)
    self.driver.find_element(By.XPATH, "//div[2]/div/div/div[3]/button[2]").click()
    time.sleep(3)
    text = self.driver.find_element(By.CSS_SELECTOR, ".toast-message").text
    
    if text != "0 enrolled users": 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return True
    else: 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return False
  
  def test_userCourse12(self):
    self.driver.get("https://school.moodledemo.net/")
    self.driver.set_window_size(783, 816)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()

    self.driver.find_element(By.ID, "password").send_keys("moodle")
    self.driver.find_element(By.ID, "loginbtn").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "#course-info-container-69-4 .multiline").click()
    self.driver.find_element(By.LINK_TEXT, "Participants").click()
    self.driver.find_element(By.CSS_SELECTOR, "#enrolusersbutton-1 .btn").click()
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "#enrolusersbutton-1 .btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.XPATH, "//div[3]/input").click()
    self.driver.find_element(By.XPATH, "//div[3]/input").send_keys("t")
    time.sleep(1)
    self.driver.find_element(By.XPATH, "//div[2]/div/div[2]/ul/li").click()
    self.driver.find_element(By.XPATH, "//div[2]/div[2]/div[3]/input").send_keys("Blue")
    time.sleep(1)
    self.driver.find_element(By.XPATH, "//div[2]/div[2]/div[2]/ul/li").click()
    time.sleep(1)
    self.driver.find_element(By.XPATH, "//div[2]/div/div/div[3]/button[2]").click()
    time.sleep(3)
    text = self.driver.find_element(By.CSS_SELECTOR, ".toast-message").text
    
    if text != "0 enrolled users": 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return True
    else: 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return False
  
  def test_userCourse13(self):
    self.driver.get("https://school.moodledemo.net/")
    self.driver.set_window_size(784, 816)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    
    self.driver.find_element(By.ID, "password").send_keys("moodle")
    self.driver.find_element(By.ID, "loginbtn").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "#course-info-container-69-4 .multiline").click()
    self.driver.find_element(By.LINK_TEXT, "Participants").click()
    self.driver.find_element(By.CSS_SELECTOR, "#enrolusersbutton-1 .btn").click()
    time.sleep(3)
    self.driver.find_element(By.XPATH, "//div[3]/input").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.XPATH, "//div[3]/input").send_keys("stephanadams175@example.com")
    self.driver.find_element(By.ID, "id_userlist_label").click()
    self.driver.find_element(By.ID, "id_cohortlist_label").click()
    self.driver.find_element(By.XPATH, "//div[2]/div[2]/div[3]/input").send_keys("Blue House")
    self.driver.find_element(By.ID, "id_cohortlist_label").click()
    time.sleep(1)
    self.driver.find_element(By.XPATH, "//div[2]/div/div/div[3]/button[2]").click()
    time.sleep(3)
    
    if self.driver.find_element(By.CSS_SELECTOR, ".toast-message").text == "0 enrolled users": 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return True
    else: 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return False
  
  def test_userCourse14(self):
    self.driver.get("https://school.moodledemo.net/")
    self.driver.set_window_size(783, 816)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()

    self.driver.find_element(By.ID, "password").send_keys("moodle")
    self.driver.find_element(By.ID, "loginbtn").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "#course-info-container-69-4 .multiline").click()
    self.driver.find_element(By.LINK_TEXT, "Participants").click()
    self.driver.find_element(By.CSS_SELECTOR, "#enrolusersbutton-1 .btn").click()
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "#enrolusersbutton-1 .btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.XPATH, "//div[3]/input").click()
    self.driver.find_element(By.XPATH, "//div[3]/input").send_keys("ste")
    time.sleep(1)
    self.driver.find_element(By.XPATH, "//div[2]/div/div[2]/ul/li").click()
    self.driver.find_element(By.XPATH, "//div[2]/div[2]/div[3]/input").send_keys("Blue House")
    time.sleep(1)
    self.driver.find_element(By.XPATH, "//div[2]/div/div/div[3]/button[2]").click()
    time.sleep(3)
    
    if self.driver.find_element(By.CSS_SELECTOR, ".toast-message").text == "0 enrolled users": 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return True
    else: 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return False
  
  def test_userCourse15(self):
    self.driver.get("https://school.moodledemo.net/")
    self.driver.set_window_size(783, 816)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()

    self.driver.find_element(By.ID, "password").send_keys("moodle")
    self.driver.find_element(By.ID, "loginbtn").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "#course-info-container-69-4 .multiline").click()
    self.driver.find_element(By.LINK_TEXT, "Participants").click()
    self.driver.find_element(By.CSS_SELECTOR, "#enrolusersbutton-1 .btn").click()
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "#enrolusersbutton-1 .btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.XPATH, "//div[3]/input").click()
    self.driver.find_element(By.XPATH, "//div[3]/input").send_keys("stevenmoreno331@example.com")
    self.driver.find_element(By.XPATH, "//div[2]/div[2]/div[3]/input").send_keys("Blue")
    time.sleep(1)
    self.driver.find_element(By.XPATH, "//div[2]/div[2]/div[2]/ul/li").click()
    time.sleep(1)
    self.driver.find_element(By.XPATH, "//div[2]/div/div/div[3]/button[2]").click()
    time.sleep(3)
    
    if self.driver.find_element(By.CSS_SELECTOR, ".toast-message").text == "0 enrolled users": 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return True
    else: 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return False
  
  def test_userCourse16(self):
    self.driver.get("https://school.moodledemo.net/")
    self.driver.set_window_size(783, 816)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()

    self.driver.find_element(By.ID, "password").send_keys("moodle")
    self.driver.find_element(By.ID, "loginbtn").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "#course-info-container-69-4 .multiline").click()
    self.driver.find_element(By.LINK_TEXT, "Participants").click()
    self.driver.find_element(By.CSS_SELECTOR, "#enrolusersbutton-1 .btn").click()
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "#enrolusersbutton-1 .btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.XPATH, "//div[3]/input").click()
    self.driver.find_element(By.XPATH, "//div[3]/input").send_keys("ad")
    time.sleep(1)
    self.driver.find_element(By.XPATH, "//div[2]/div/div[2]/ul/li").click()
    self.driver.find_element(By.XPATH, "//div[2]/div[2]/div[3]/input").send_keys("Blue")
    time.sleep(1)
    self.driver.find_element(By.XPATH, "//div[2]/div[2]/div[2]/ul/li").click()
    time.sleep(1)
    self.driver.find_element(By.XPATH, "//div[2]/div/div/div[3]/button[2]").click()
    time.sleep(3)
    text = self.driver.find_element(By.CSS_SELECTOR, ".toast-message").text
    
    if text != "0 enrolled users": 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return True
    else: 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return False
  
  def test_userCourse17(self):
    self.driver.get("https://school.moodledemo.net/")
    self.driver.set_window_size(784, 816)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    
    self.driver.find_element(By.ID, "password").send_keys("moodle")
    self.driver.find_element(By.ID, "loginbtn").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "#course-info-container-69-4 .multiline").click()
    self.driver.find_element(By.LINK_TEXT, "Participants").click()
    self.driver.find_element(By.CSS_SELECTOR, "#enrolusersbutton-1 .btn").click()
    time.sleep(3)
    self.driver.find_element(By.XPATH, "//div[3]/input").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.XPATH, "//div[3]/input").send_keys("abc@example.com")
    time.sleep(1)
    self.driver.find_element(By.XPATH, "//div[2]/div/div/div[3]/button[2]").click()
    time.sleep(3)
    
    if self.driver.find_element(By.CSS_SELECTOR, ".toast-message").text == "0 enrolled users": 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return True
    else: 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return False
  
  def test_userCourse18(self):
    self.driver.get("https://school.moodledemo.net/")
    self.driver.set_window_size(784, 816)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    
    self.driver.find_element(By.ID, "password").send_keys("moodle")
    self.driver.find_element(By.ID, "loginbtn").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "#course-info-container-69-4 .multiline").click()
    self.driver.find_element(By.LINK_TEXT, "Participants").click()
    self.driver.find_element(By.CSS_SELECTOR, "#enrolusersbutton-1 .btn").click()
    time.sleep(3)
    self.driver.find_element(By.XPATH, "//div[3]/input").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.XPATH, "//div[3]/input").send_keys("stephanadams175@example.com")
    self.driver.find_element(By.ID, "id_userlist_label").click()
    self.driver.find_element(By.ID, "id_cohortlist_label").click()
    self.driver.find_element(By.XPATH, "//div[2]/div[2]/div[3]/input").send_keys("abc")
    self.driver.find_element(By.ID, "id_cohortlist_label").click()
    time.sleep(1)
    self.driver.find_element(By.XPATH, "//div[2]/div/div/div[3]/button[2]").click()
    time.sleep(3)
    
    if self.driver.find_element(By.CSS_SELECTOR, ".toast-message").text == "0 enrolled users": 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return True
    else: 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return False
  
  def test_userCourse19(self):
    self.driver.get("https://school.moodledemo.net/")
    self.driver.set_window_size(784, 816)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    
    self.driver.find_element(By.ID, "password").send_keys("moodle")
    self.driver.find_element(By.ID, "loginbtn").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "#course-info-container-69-4 .multiline").click()
    self.driver.find_element(By.LINK_TEXT, "Participants").click()
    self.driver.find_element(By.CSS_SELECTOR, "#enrolusersbutton-1 .btn").click()
    time.sleep(3)
    self.driver.find_element(By.XPATH, "//div[3]/input").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.XPATH, "//div[3]/input").send_keys("a")
    time.sleep(1)
    self.driver.find_element(By.XPATH, "//div[2]/div/div[2]/ul/li").click()
    self.driver.find_element(By.XPATH, "//div[2]/div[2]/div[3]/input").send_keys("abc")
    self.driver.find_element(By.ID, "id_cohortlist_label").click()
    time.sleep(1)
    self.driver.find_element(By.XPATH, "//div[2]/div/div/div[3]/button[2]").click()
    time.sleep(3)
    
    if self.driver.find_element(By.CSS_SELECTOR, ".toast-message").text == "0 enrolled users": 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return True
    else: 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return False
  
  def test_userCourse3(self):
    self.driver.get("https://school.moodledemo.net/")
    self.driver.set_window_size(784, 816)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    
    self.driver.find_element(By.ID, "password").send_keys("moodle")
    self.driver.find_element(By.ID, "loginbtn").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "#course-info-container-69-4 .multiline").click()
    self.driver.find_element(By.LINK_TEXT, "Participants").click()
    self.driver.find_element(By.CSS_SELECTOR, "#enrolusersbutton-1 .btn").click()
    time.sleep(3)
    self.driver.find_element(By.XPATH, "//div[3]/input").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.XPATH, "//div[3]/input").send_keys("thomas@example.com")
    self.driver.find_element(By.ID, "id_userlist_label").click()
    self.driver.find_element(By.ID, "id_cohortlist_label").click()
    self.driver.find_element(By.XPATH, "//div[2]/div[2]/div[3]/input").send_keys("")
    self.driver.find_element(By.ID, "id_cohortlist_label").click()
    self.driver.find_element(By.ID, "id_roletoassign").click()
    time.sleep(1)
    self.driver.find_element(By.XPATH, "//div[2]/div/div/div[3]/button[2]").click()
    time.sleep(3)
    self.driver.execute_script("window.scrollTo(0,400)")
    
    if self.driver.find_element(By.CSS_SELECTOR, ".toast-message").text == "0 enrolled users": 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return True
    else: 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return False
  
  def test_userCourse6(self):
    self.driver.get("https://school.moodledemo.net/")
    self.driver.set_window_size(784, 816)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    
    self.driver.find_element(By.ID, "password").send_keys("moodle")
    self.driver.find_element(By.ID, "loginbtn").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "#course-info-container-69-4 .multiline").click()
    self.driver.find_element(By.LINK_TEXT, "Participants").click()
    self.driver.find_element(By.CSS_SELECTOR, "#enrolusersbutton-1 .btn").click()
    time.sleep(3)
    self.driver.find_element(By.XPATH, "//div[3]/input").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.XPATH, "//div[3]/input").send_keys("")
    self.driver.find_element(By.ID, "id_userlist_label").click()
    self.driver.find_element(By.ID, "id_cohortlist_label").click()
    self.driver.find_element(By.XPATH, "//div[2]/div[2]/div[3]/input").send_keys("Green House")
    self.driver.find_element(By.ID, "id_cohortlist_label").click()
    self.driver.find_element(By.ID, "id_roletoassign").click()
    dropdown = self.driver.find_element(By.ID, "id_roletoassign")
    select = Select(dropdown)
    select.select_by_value('4')
    time.sleep(1)
    self.driver.find_element(By.XPATH, "//div[2]/div/div/div[3]/button[2]").click()
    time.sleep(3)
    self.driver.execute_script("window.scrollTo(0,400)")
    self.driver.find_element(By.XPATH, "//div[3]/table/tbody/tr/td[2]").click()
    
    if self.driver.find_element(By.CSS_SELECTOR, ".toast-message").text == "0 enrolled users": 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return True
    else: 
      self.driver.find_element(By.ID, "user-menu-toggle").click()
      self.driver.find_element(By.LINK_TEXT, "Log out").click()
      return False
  
  def test(self, *test_list):
    result = []
    for test in test_list:
        result.append(test())
    fail_test_name = []
    for i in range(0, len(result)):
        if not result[i]:
            fail_test_name.append(test_list[i].__name__)

    fail_test_name_str = 'FAILED:\n\t'+ '\n\t'.join(name for name in fail_test_name) if len(fail_test_name) != 0 else 'Fail testcase: None'
    return f"""
    \n- Test Add User To Course --\nPASSED: {result.count(True)}/{len(result)}\n{fail_test_name_str}\n
    """
    
  def run(self):

    self.setup_method(None)

    result = self.test(
      self.test_userCourse1,
      self.test_userCourse2,
      self.test_userCourse3,
      self.test_userCourse4,
      self.test_userCourse5,
      self.test_userCourse6,
      self.test_userCourse7,
      self.test_userCourse8,
      self.test_userCourse9,
      self.test_userCourse10,
      self.test_userCourse11,
      self.test_userCourse12,
      self.test_userCourse13,
      self.test_userCourse14,
      self.test_userCourse15,
      self.test_userCourse16,
      self.test_userCourse17,
      self.test_userCourse18,
      self.test_userCourse19,
    )

    self.teardown_method(None)

    return result
  
userCourse = TestUserCourse()
print(userCourse.run())